# Generated by Django 2.2.7 on 2019-11-19 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbank_id', models.CharField(max_length=50)),
                ('smiles', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adr.Feature')),
                ('adr_id', models.CharField(max_length=50)),
            ],
            bases=('adr.feature',),
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adr.Feature')),
                ('indication_id', models.CharField(max_length=50)),
            ],
            bases=('adr.feature',),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adr.Feature')),
                ('target_id', models.CharField(max_length=50)),
            ],
            bases=('adr.feature',),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(max_length=50)),
                ('weight_value', models.FloatField(null=True)),
                ('weight_units', models.CharField(max_length=50, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adr.Drug')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adr.Feature')),
            ],
        ),
    ]
