# Generated by Django 2.2.7 on 2019-11-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='smiles',
            field=models.CharField(max_length=10000),
        ),
    ]
