# Generated by Django 2.2.7 on 2019-12-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0005_drug_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='feature_id',
            new_name='feature',
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugbank_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
