# Generated by Django 2.2.7 on 2019-12-07 22:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0006_auto_20191207_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketMotif',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adr.Feature')),
                ('motif_id', models.IntegerField()),
                ('proteins', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
            bases=('adr.feature',),
        ),
    ]
